data_ingestion:
  data_source: "local"
  source: "src/data/data.txt"
  artifact_dir: "./artifacts"
  train_ratio: 0.8
  validation_ratio: 0.1
  test_ratio: 0.1

data_processing:
  shift: 18

model_trainer:
  n_estimators: 500
  max_samples: 0.8
  max_depth: 40


  