data_ingestion:
  data_source: "local"
  source: "src/data/data.txt"
  artifact_dir: "./artifacts"
  train_ratio: 0.8
  validation_ratio: 0.1
  test_ratio: 0.1

data_processing:
  shift: 18

model_trainer:
  n_estimators: 500
  max_samples: 0.8
  max_depth: 40
  save_model_path: "./artifacts/models"
  experiment_name: "Tap30Challenge"

web:
  host: "127.0.0.1"
  port: 8000
  model: 'artifacts/models'
  model_name: 'model.joblib'
  


  